### ISSUE TITLE
xenon rejoin  xenon cluster is  INVALID

### ISSUE THREAD

**Issue by deep-cds** [radondb/xenon#144]
你好 、 xenon 研发同学。 

![image](https://user-images.githubusercontent.com/44251514/123506414-a1a02e80-d696-11eb-96f6-7fecbe280bbb.png)

**Comment by caphash** [comment]
你好，问题可以分为两个部分解答：

1. xenoncli 执行 timeout：

通过以下日志可以看到 xenon 配置 RequestTimeout 为 0.5 秒过小，在通常的网络条件下建议不小于 1 秒 并设置为 ElectionTimeout/AdmitDefeatHtCnt 的值。

`2021/06/26 16:00:42.380790 [WARNING] xenon.conf.raft:[&{MetaDatadir:raft.meta HeartbeatTimeout:1000 AdmitDefeatHtCnt:10 ElectionTimeout:3000 PurgeBinlogInterval:300000 SuperIDLE:false LeaderStartCommand: LeaderStopCommand: PurgeBinlogDisabled:false RequestTimeout:500 CandidateWaitFor2Nodes:60000}]
2021/06/26 16:00:42.380826 [WARNING] xenon.conf.mysql:[&{Admin:root Passwd:DOVYJ2gveVIirLzE Host:127.0.0.1 Port:3306 Basedir:/data/mysql8.0.22 Version:mysql57 DefaultsFile:/data/mysql8.0.22/config/my.cnf PingTimeout:1000 AdmitDefeatPingCnt:2 MasterSysVars: SlaveSysVars: ReplHost:192.168.39.167 ReplUser:repl ReplPasswd:replication}]
2021/06/26 16:00:42.380866 [WARNING] xenon.conf.mysqld:[&{SSHHost:192.168.39.167 SSHUser:root SSHPasswd:nnSnRp+xBKOFmSjF SSHPort:22 BackupDir:/data/mysql8.0.22/data XtrabackupBinDir:/usr/bin BackupIOPSLimits:100000 UseMemory:2GB Parallel:2 MysqldMonitorInterval:1000 Admin:root Passwd:DOVYJ2gveVIirLzE Host:127.0.0.1 Port:3306 Basedir:/data/mysql8.0.22 DefaultsFile:/data/mysql8.0.22/config/my.cnf}]`

2. 主从发生过切换且原主 `192.168.39.167` 状态变为 INVALID：

这是由于主节点写数据时切换，leader 在降级后存在脏事务，当 xenon 检测到时自动将原主设置为 INVALID 状态，出现该情况后可以通过 `./xenoncli mysql rebuildme` 进行数据重建，之后恢复为 FOLLOWER 状态。

另外，可以适当调大 HeartbeatTimeout、ElectionTimeout 等参数，并使用 xenon 最新版降低误切换可能性。

**Comment by Lzw901** [comment]
[mysql@localhost /usr/local/xenon/bin]$ ./xenoncli mysql rebuildme --from=10.232.2.187:8801
 2024/04/15 17:46:19.903706 	  [WARNING]  	=====prepare.to.rebuildme=====
			IMPORTANT: Please check that the backup run completes successfully.
			           At the end of a successful backup run innobackupex
			           prints "completed OK!".
			
 2024/04/15 17:46:19.904072 	  [WARNING]  	S1-->check.raft.leader
 2024/04/15 17:46:19.906042 	  [WARNING]  	S2-->prepare.rebuild.from[10.232.2.187:8801]....
 2024/04/15 17:46:19.908912 	  [PANIC]  	 I[10.232.2.188:8801].have.[2].local.transactions.more.than.maxAllowedLocalTrxCount[0].compared.to.from[10.232.2.187:8801].you.cant.rebuildme.sir
panic: 	  [PANIC]  	 I[10.232.2.188:8801].have.[2].local.transactions.more.than.maxAllowedLocalTrxCount[0].compared.to.from[10.232.2.187:8801].you.cant.rebuildme.sir

goroutine 1 [running]:
xbase/xlog.(*Log).Panic(0xc0001862e0, {0x7b2085, 0x7fffa76da2da}, {0xc000121db0, 0xc000190750, 0x0})
	/root/xenon-1.1.4/src/xbase/xlog/xlog.go:142 +0xc8
cli/cmd.mysqlRebuildMeCommandFn(0xc0001e6b40, {0xc000186370, 0x1, 0x1})
	/root/xenon-1.1.4/src/cli/cmd/mysql.go:269 +0x438
vendor/github.com/spf13/cobra.(*Command).execute(0xc0001e6b40, {0xc000186350, 0x1, 0x1})
	/root/xenon-1.1.4/src/vendor/github.com/spf13/cobra/command.go:603 +0x3a7
vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xa5b720)
	/root/xenon-1.1.4/src/vendor/github.com/spf13/cobra/command.go:689 +0x24b
vendor/github.com/spf13/cobra.(*Command).Execute(...)
	/root/xenon-1.1.4/src/vendor/github.com/spf13/cobra/command.go:648
main.main()
	/root/xenon-1.1.4/src/cli/cli.go:43 +0x25
	
	
重建节点时报错这个是什么原因？
