### ISSUE TITLE
按照官方手册编译安装后，报错

### ISSUE THREAD

**Issue by zhusas** [radondb/xenon#152]
-bash-4.2$ ./xenon -c /etc/xenon/xenon.json
xenon:[{Tag: Time:2021/12/03 03:09:25 Git: GoVersion:go1.17.3 Platform:linux amd64}]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x6fa242]

goroutine 1 [running]:
xbase/xlog.(*Log).Panic(0x7ffd03b2f8c0, {0x86cfc4, 0x863a11}, {0xc0000a3e08, 0xc0000a3df8, 0x1})
	/opt/tools/xenon/src/xbase/xlog/xlog.go:137 +0x22
main.main()
	/opt/tools/xenon/src/xenon/xenon.go:54 +0x354
-bash-4.2$ 

求解

**Comment by Myshiner** [comment]
我今天也遇到这个问题了，我看看你的xenon.json配置
