### ISSUE TITLE
 xenoncli mysql backup 报错

### ISSUE THREAD

**Issue by yukai701** [radondb/xenon#172]
[mysql@mysqlcluster01 bin]$ xenoncli version
xenoncli:[{Tag: Time:2023/01/04 12:05:09 Git: GoVersion:go1.18.9 Platform:linux amd64}]

os：CentOS Linux release 7.8.2003 (Core)
db:mysql 5.7.37-log
报错信息：
[mysql@mysqlcluster01 bin]$ xenoncli mysql backup --to=/data/backup 
 2023/01/05 16:59:34.501196       [WARNING]     rebuildme.found.best.slave[192.168.1.42:8801].leader[192.168.1.41:8801]
 2023/01/05 16:59:34.501315       [WARNING]     S1-->found.the.best.backup.host[192.168.1.42:8801]....
mysql.go:575: unexpected error: exit status 1

 2023/01/05 16:59:34.511271       [PANIC]        exit status 1
panic:    [PANIC]        exit status 1

goroutine 1 [running]:
xbase/xlog.(*Log).Panic(0xc0001862f0, {0x7a9de5?, 0x7bbe9c?}, {0xc00012dcd8?, 0xc00012dce8?, 0x3?})
        /usr/local/xenon-1.1.4/src/xbase/xlog/xlog.go:142 +0xc8
cli/cmd.ErrorOK({0x8439c0, 0xc000192b40})
        /usr/local/xenon-1.1.4/src/cli/cmd/common.go:35 +0x192
cli/cmd.mysqlDoBackupCommandFn(0xc0001e4d80?, {0xc000186380?, 0x1?, 0x1?})
        /usr/local/xenon-1.1.4/src/cli/cmd/mysql.go:575 +0x1e5
vendor/github.com/spf13/cobra.(*Command).execute(0xc0001e4d80, {0xc000186360, 0x1, 0x1})
        /usr/local/xenon-1.1.4/src/vendor/github.com/spf13/cobra/command.go:603 +0x3e7
vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xa48dc0)
        /usr/local/xenon-1.1.4/src/vendor/github.com/spf13/cobra/command.go:689 +0x248
vendor/github.com/spf13/cobra.(*Command).Execute(...)
        /usr/local/xenon-1.1.4/src/vendor/github.com/spf13/cobra/command.go:648
main.main()
        /usr/local/xenon-1.1.4/src/cli/cli.go:43 +0x25
[mysql@mysqlcluster01 bin]$ xenoncli mysql backup --to=/data/backup 
 2023/01/05 17:00:47.753080       [WARNING]     rebuildme.found.best.slave[192.168.1.42:8801].leader[192.168.1.41:8801]
 2023/01/05 17:00:47.753290       [WARNING]     S1-->found.the.best.backup.host[192.168.1.42:8801]....
mysql.go:575: unexpected error: exit status 1

 2023/01/05 17:00:47.763593       [PANIC]        exit status 1
panic:    [PANIC]        exit status 1

goroutine 1 [running]:
xbase/xlog.(*Log).Panic(0xc000090300, {0x7a9de5?, 0x7bbe9c?}, {0xc000125cd8?, 0xc000125ce8?, 0x3?})
        /usr/local/xenon-1.1.4/src/xbase/xlog/xlog.go:142 +0xc8
cli/cmd.ErrorOK({0x8439c0, 0xc000190280})
        /usr/local/xenon-1.1.4/src/cli/cmd/common.go:35 +0x192
cli/cmd.mysqlDoBackupCommandFn(0xc0000eed80?, {0xc000090390?, 0x1?, 0x1?})
        /usr/local/xenon-1.1.4/src/cli/cmd/mysql.go:575 +0x1e5
vendor/github.com/spf13/cobra.(*Command).execute(0xc0000eed80, {0xc000090370, 0x1, 0x1})
        /usr/local/xenon-1.1.4/src/vendor/github.com/spf13/cobra/command.go:603 +0x3e7
vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xa48dc0)
        /usr/local/xenon-1.1.4/src/vendor/github.com/spf13/cobra/command.go:689 +0x248
vendor/github.com/spf13/cobra.(*Command).Execute(...)
        /usr/local/xenon-1.1.4/src/vendor/github.com/spf13/cobra/command.go:648
main.main()
        /usr/local/xenon-1.1.4/src/cli/cli.go:43 +0x25

**Comment by bookgh** [comment]
> 1.  创建备份目录&& 授权给 mysql 用户
mkdir -p /backup/mysql
chown -Rf mysql:mysql /backup

> 2.  以 mysql 用户身份执行备份
su mysql -lc '/usr/local/bin/xenoncli mysql backup --to /backup/mysql/test'

> 3.  如果备份报错找不到 config.path 文件执行以下命令（根据软件实际安装路径，配置文件路径执行）
echo '/etc/xenon/xenon.json' > /usr/local/bin/config.path
